fix: using mathematics in commands and rpcs (#492)
Generating readers and writers for structs in other assemblies
could sometimes cause a
```
System.ArgumentException: Member 'xxx' is declared in another module and needs to be imported
```

This in particular affected unity mathematics.